<?php

namespace Doctrine\Bundle\PHPCRBundle\EventListener;

use Doctrine\ORM\Tools\Event\GenerateSchemaEventArgs;
use Psr\Container\ContainerInterface;

/**
 * Merges the Jackalope doctrine dbal schema into a schema generated by
 * Doctrine ORM.
 *
 * This is used to avoid clashes with the Doctrine ORM if both are used in
 * parallel.
 *
 * @author David Buchmann <mail@davidbu.ch>
 * @author Johannes M. Schmitt <schmittjoh@gmail.com>
 */
class JackalopeDoctrineDbalSchemaListener
{
    private $container;

    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }

    public function postGenerateSchema(GenerateSchemaEventArgs $args)
    {
        $schema = $args->getSchema();
        $this->container->get('doctrine_phpcr.jackalope_doctrine_dbal.schema')->addToSchema($schema);
    }
}
